// packages/wallet-frontend/src/Petname.svelte
<script>
  export let name;
  export let board = undefined;
  export let plural = false;
</script>

<style>
  .confirmedPetname {
    /* color: green; */
  }
  .untrustedName {
    color: orange;
  }
</style>

{#if Array.isArray(name)}
  <span class="confirmedPetname">{name[0]}</span><span class="untrustedName">
    {#each name.slice(1) as path}.{path}{#if plural}s{/if}{/each}
  </span>
{:else}
  <span class="confirmedPetname">
    {name}{#if plural}s{/if}
  </span>
  {#if board}(Board Id: {board}){/if}
{/if}

// packages/dapp-wallet/ui/src/components/Petname.jsx
import clsx from 'clsx';

import './Petname.scss';

const Petname = ({ name, plural = false, color = true }) => {
  if (Array.isArray(name)) {
    return (
      <span>
        {name[0]}
        <span className={clsx(color && 'Color', 'UntrustedName')}>
          {name.slice(1).map(chunk => `.${chunk}`)}
          {plural && 's'}
        </span>
      </span>
    );
  }

  return (
    <span>
      {name}
      {plural && 's'}
    </span>
  );
};

export default Petname;
