// packages/dapp-wallet/ui/src/components/Dapp.jsx
import { useState, useEffect } from 'react';
import TextField from '@mui/material/TextField';
import { E } from '@agoric/eventual-send';
import { withApplicationContext } from '../contexts/Application';

const DappWithoutContext = ({ dapp, dapps }) => {
  const { petname, origin, dappOrigin, enable, actions } = dapp;
  const [dappPetname, setDappPetname] = useState(petname);
  const [isValid, setIsValid] = useState(true);

  useEffect(() => {
    setIsValid(
      petname === dappPetname ||
        !dapps.filter(
          ({ petname: otherPetname }) => dappPetname === otherPetname,
        ).length,
    );
  }, [dappPetname]);

  const handleDappPetnameChange = event => setDappPetname(event.target.value);

  const handleKeydown = event => {
    if (event.key === 'Escape') {
      setDappPetname(petname);
      event.stopPropagation();
    } else if (event.key === 'Enter') {
      E(actions).setPetname(dappPetname);
      event.stopPropagation();
    }
  };

  return (
    <>
      <div style={{ marginBottom: '8px', fontWeight: '700' }}>
        <span>{petname}</span>{' '}
      </div>
      <div className="text-gray">
        {enable ? 'User' : 'Alleged user'} interface:{' '}
        <span className="Blue">{dappOrigin || origin}</span>
      </div>
      <div style={{ height: '64px' }}>
        <TextField
          spellCheck="false"
          margin="dense"
          size="small"
          label="Dapp petname"
          fullWidth
          variant="standard"
          value={dappPetname}
          error={!isValid}
          helperText={!isValid && 'Petname already in use'}
          onKeyDown={handleKeydown}
          onChange={handleDappPetnameChange}
        />
      </div>
    </>
  );
};

export default withApplicationContext(DappWithoutContext, context => ({
  dapps: context.dapps,
}));

// packages/dapp-svelte-wallet/ui/src/Dapp.svelte
<script>
  import { E } from "@agoric/eventual-send";
  import TextField from 'smelte/src/components/TextField';
  import Switch from 'smelte/src/components/Switch';

  export let item;
  export let details = true;
  export let summary = true;

  $: ({ enable, actions, suggestedPetname,
    petname: origPetname, dappOrigin, origin } = item);
  let petname = item.petname || item.suggestedPetname;

  const toggleDappEnabled = () => {
    if (enable) {
      E(E(actions).setPetname(petname)).disable();
    } else {
      E(E(actions).setPetname(petname)).enable();
    }
  };

  const keydown = ev => {
    if (ev.key === 'Escape') {
      petname = origPetname;
      ev.stopPropagation();
    } else if (ev.key === 'Enter') {
      E(actions).setPetname(petname);
      ev.stopPropagation();
    }
  };
</script>

<div>
{#if summary}{origPetname}{/if}
{#if details}
  <div>
    {#if enable}
    User interface: <a target="_blank" href={dappOrigin || origin}>{dappOrigin || origin}</a>
    {:else}
    Alleged user interface: <strikethrough>{dappOrigin || origin}</strikethrough>
    {/if}
  </div>
  <div on:keydown|capture={keydown}><TextField
    hint="Alleged name: {JSON.stringify(suggestedPetname)}"
    label="Dapp petname"
    bind:value={petname}
  /></div>
  <div on:click|capture|stopPropagation={toggleDappEnabled}>
    <Switch value={enable} label="Enabled" />
  </div>
{/if}
</div>
