// packages/dapp-wallet/ui/src/components/Petname.jsx
import clsx from 'clsx';

import './Petname.scss';

const Petname = ({ name, plural = false, color = true }) => {
  if (Array.isArray(name)) {
    return (
      <span>
        {name[0]}
        <span className={clsx(color && 'Color', 'UntrustedName')}>
          {name.slice(1).map(chunk => `.${chunk}`)}
          {plural && 's'}
        </span>
      </span>
    );
  }

  return (
    <span>
      {name}
      {plural && 's'}
    </span>
  );
};

export default Petname;

// packages/dapp-svelte-wallet/ui/src/Petname.svelte
<script>
  export let name;
  export let board = undefined;
  export let plural = false;
  export let color = true;
</script>

<style>
  /*
  .confirmedPetname.color {
    color: green;
  }
  */
  .untrustedName.color {
    color: rgb(194, 50, 50);
  }
</style>

{#if Array.isArray(name)}
  <span class:color class="confirmedPetname">{name[0]}</span><span class:color class="untrustedName">
    {#each name.slice(1) as path}.{path}{/each}{#if plural}s{/if}
  </span>
{:else}
  <span class:color class="confirmedPetname">
    {name}{#if plural}s{/if}
  </span>
  {#if board}(Board Id: {board}){/if}
{/if}
