// packages/dapp-wallet/ui/src/components/Requests.jsx
import Offer from './Offer';
import Payment from './Payment';
import DappConnection from './DappConnection';
import { withApplicationContext } from '../contexts/Application';

import './Requests.scss';

// Exported for testing only.
const RequestsInternal = ({
  payments,
  offers,
  dapps,
  purses,
  pendingOffers,
  declinedOffers,
  closedOffers,
}) => {
  const hasNoAutodeposit = payment =>
    payment.status !== 'deposited' &&
    !purses.filter(
      p => p.brand === payment.brand && (p.depositBoardId || '').length,
    ).length;

  const isDisabled = dapp => !dapp.enable;

  payments = (payments || [])
    .filter(hasNoAutodeposit)
    .map(p => ({ type: 'payment', data: p }));

  offers = (offers || [])
    .filter(
      ({ status, id }) =>
        ((status || 'proposed') === 'proposed' ||
          (status || 'proposed') === 'pending' ||
          pendingOffers.has(id) ||
          declinedOffers.has(id)) &&
        !closedOffers.has(id),
    )
    .map(o => ({
      type: 'offer',
      data: o,
    }));

  dapps = (dapps || []).filter(isDisabled).map(d => ({
    type: 'dapp',
    data: d,
  }));

  const requests = [...payments, ...offers, ...dapps].sort(
    (a, b) => a.data.id - b.data.id,
  );

  const Item = request => {
    if (request.type === 'offer') {
      return <Offer offer={request.data} key={request.data.id} />;
    } else if (request.type === 'payment') {
      return <Payment key={request.data.id} />;
    } else {
      return <DappConnection dapp={request.data} key={request.data.id} />;
    }
  };
  return (
    <div className="Requests">
      {requests.length ? (
        requests.map(Item)
      ) : (
        <div className="Empty">
          <img
            className="Splash-image"
            src="agoric-city.svg"
            alt="Empty Inbox"
            width="320"
            height="320"
          />
          <p className="text-gray">No requests</p>
        </div>
      )}
    </div>
  );
};

export default withApplicationContext(RequestsInternal, context => ({
  payments: context.payments,
  offers: context.inbox,
  dapps: context.dapps,
  purses: context.purses,
  pendingOffers: context.pendingOffers,
  declinedOffers: context.declinedOffers,
  closedOffers: context.closedOffers,
}));

// packages/dapp-svelte-wallet/ui/src/Requests.svelte

<script>
    import TransactionV2 from './TransactionV2.svelte';
    import DappV2 from './DappV2.svelte';
    import PaymentV2 from './PaymentV2.svelte';

    import { inbox, dapps, payments, purses } from './store';

    export let classes = '';

    const hasAutoDeposit = (payment) =>
        $purses.filter((p) =>
            p.brand === payment.brand && (p.depositBoardId || '').length
        ).length;

    $: incomingPayments = ($payments || []).filter((i) => i.status !== 'deposited' && !hasAutoDeposit(i));
    $: offers = ($inbox || []).filter(({ status }) => status === undefined || status === 'pending');
    $: dappConnections = ($dapps || []).filter(({ enable }) => !enable);

    $: mappedPayments = incomingPayments.map((i) => {
        return {
            type: 'payment',
            data: i,
            id: i.displayPayment.payment.petname,
        };
    });
    $: mappedOffers = offers.map((i) => { 
        return {
            type: 'transaction',
            data: i,
            id: i.id,
        };
    });
    $: mappedDapps = dappConnections.map((i) => { 
        return {
            type: 'dapp',
            data: i,
            id: i.dappOrigin || i.origin,
        };
    });

    $: items = [...mappedPayments, ...mappedOffers, ...mappedDapps];
</script>

<style>
    .splash-image {
        opacity: 0.6;
    }

    .content {
        align-items: center;
        display: flex;
        flex-direction: column;
        justify-content: flex-start;
    }

    h6 {
        font-size: 18px;
    }

    .empty {
        animation: fadeIn 2s;
        text-align: center;
    }

    @keyframes fadeIn {
        0% { opacity: 0; }
        5% { opacity: 0; }
        100% { opacity: 1; }
    }
</style>
 
<div class={`content ${classes}`}>
    {#if items.length}
        {#each items as item (item.id)}
            {#if item.type === "transaction"}
                <TransactionV2 item={item.data} />
            {:else if item.type === "payment"}
                <PaymentV2 item={item.data} />
            {:else}
                <DappV2 item={item.data} />
            {/if}
        {/each}
    {:else}
        <div class="empty">
            <img class="splash-image"
                src="generic-agoric.svg"
                alt="Empty Inbox"
                width="320"
                height="320" />
            <p class="text-gray-700">
                No requests.
            </p>
        </div>
    {/if}
</div>
