// packages/dapp-svelte-wallet/ui/src/Amount.svelte
<script>
  import Petname from "./Petname.svelte";
  import Debug from "../lib/Debug.svelte";
  import Tooltip from "../lib/Tooltip.svelte";

  export let amount;

  // The amount gets updated. Make this dynamic
  $: ({ brand, value } = amount);
  const cardinality = v => typeof v === 'number' ? v : v.length;
</script>

<style>
  section, div {
    display: inline;
  }
</style>

<section>
  {#if Array.isArray(value) && value.length !== 0}
    <!-- amount is non-fungible -->
    <Tooltip>
      <div slot="activator">
        <b>
          {value.length}
          <Petname name={brand.petname} plural={value.length !== 1} />
        </b>
      </div>
      {#if brand.petname === 'zoe invite'}
        {#each value as { instanceHandle: { petname }, inviteDesc }}
          instance: {petname}, inviteDesc: {inviteDesc}
        {/each}
      {:else}
        {#each value as elem (elem)}{JSON.stringify(elem)}{/each}
      {/if}
    </Tooltip>
  {:else}
    <b>
      {cardinality(value)}
      <Petname name={brand.petname} plural={cardinality(value) !== 1} />
    </b>
  {/if}

</section>

// packages/dapp-react-wallet/src/components/Amount.jsx
import React from 'react';

import {
  List,
  ListItem,
  ListItemText,
} from '@material-ui/core';

const displayNonfungible = amount => {
  const { brand, value } = amount;

  // TODO: base this on brandBoardId instead since petnames can change
  if (brand.petname === 'zoe invite') {
    if (value.length === 0) {
      return `${JSON.stringify(brand.petname)} purse is empty.`;
    }
    const elems = value.map(elem => {
      return {
        instance: elem.instanceHandle.petname,
        inviteDesc: elem.inviteDesc,
      };
    });
    return (
      <div>
        <b> 
{' '}
{brand.petname} (Non-fungible)</b>
        <List>
          {elems.map(({ instance, inviteDesc }) => (
            <ListItem key={inviteDesc} value={inviteDesc} divider>
              <ListItemText
                primary={`instance: ${instance}`}
                secondary={`inviteDesc: ${inviteDesc}`}
              />
            </ListItem>
          ))}
        </List>
      </div>
    );
  }
  return (
    <div>
      <b>
{brand.petname} (Non-fungible)</b>
      <List>
        {value.map(elem => (
          <ListItem key={JSON.stringify(elem)} divider>
            <ListItemText primary={JSON.stringify(elem)} />
          </ListItem>
        ))}
      </List>
    </div>
  );
};

export default function Amount({ amount }) {
  return (
    <>
      {Array.isArray(amount.value) ? (
        displayNonfungible(amount)
      ) : (
        <b>
          {' '}
          {amount.value} 
{' '}
{amount.brand.petname}
        </b>
      )}
    </>
  );
}
