// packages/wallet-frontend/src/Amount.svelte
<script>
  import Petname from './Petname.svelte';
  export let amount;

  // The amount gets updated. Make this dynamic
  $: ({ brand, value } = amount);
</script>

<main>
  {#if Array.isArray(value)}
    {#if value.length === 0}
      <b><Petname name={brand.petname} /> purse is empty.</b>
    {:else if brand.petname === 'zoe invite'}
      <b><Petname name={brand.petname} /> (Non-fungible)</b>
      {#each value as { instanceHandle: { petname }, inviteDesc } (petname)}
        instance: {petname}, inviteDesc: {inviteDesc}
      {/each}
    {:else}
      <b><Petname name={brand.petname}/> (Non-fungible)</b>
      {#each value as elem (elem)}{JSON.stringify(elem)}{/each}
    {/if}
  {:else}
    <b>{value} <Petname name={brand.petname} /></b>
  {/if}
</main>

// packages/dapp-react-wallet/src/components/Amount.jsx
import React from 'react';

import {
  List,
  ListItem,
  ListItemText,
} from '@material-ui/core';

const displayNonfungible = amount => {
  const { brand, value } = amount;

  // TODO: base this on brandBoardId instead since petnames can change
  if (brand.petname === 'zoe invite') {
    if (value.length === 0) {
      return `${JSON.stringify(brand.petname)} purse is empty.`;
    }
    const elems = value.map(elem => {
      return {
        instance: elem.instanceHandle.petname,
        inviteDesc: elem.inviteDesc,
      };
    });
    return (
      <div>
        <b> 
{' '}
{brand.petname} (Non-fungible)</b>
        <List>
          {elems.map(({ instance, inviteDesc }) => (
            <ListItem key={inviteDesc} value={inviteDesc} divider>
              <ListItemText
                primary={`instance: ${instance}`}
                secondary={`inviteDesc: ${inviteDesc}`}
              />
            </ListItem>
          ))}
        </List>
      </div>
    );
  }
  return (
    <div>
      <b>
{brand.petname} (Non-fungible)</b>
      <List>
        {value.map(elem => (
          <ListItem key={JSON.stringify(elem)} divider>
            <ListItemText primary={JSON.stringify(elem)} />
          </ListItem>
        ))}
      </List>
    </div>
  );
};

export default function Amount({ amount }) {
  return (
    <>
      {Array.isArray(amount.value) ? (
        displayNonfungible(amount)
      ) : (
        <b>
          {' '}
          {amount.value} 
{' '}
{amount.brand.petname}
        </b>
      )}
    </>
  );
}
